### ISSUE TITLE
Weird Formatting in Canvas

### ISSUE THREAD

**Issue by ssweetser86** [learn-co-curriculum/ruby-oo-class-variables-private-methods#1]
![PMissue](https://user-images.githubusercontent.com/73085282/98173999-19c8a280-1ec2-11eb-8672-007cee7bd973.PNG)

Not sure if this is just an issue with me or as a whole, but the attached screenshot is how this shows up in my canvas. I looked at the readme on github as a workaround but wanted to make someone else aware of the issue.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Please note, however, that if you are working in Canvas the changes may not appear right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
